# Generated by Django 6.1 on 2026-08-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FasilitasItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks', models.TextField(help_text='Isi poin fasilitas. Boleh multi-baris.')),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fasilitas',
                'verbose_name_plural': 'Fasilitas',
                'ordering': ['urutan', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_baris1', models.CharField(default='Magang', max_length=100)),
                ('judul_baris2', models.CharField(default='Kuy!', max_length=100)),
                ('subjudul', models.CharField(default='Kamu siswa SMK atau Mahasiswa? Cari tempat PKL, Magang, Prakerin, OJT atau praktik Kerja?', max_length=300)),
                ('deskripsi', models.TextField(default='Seven Inc membuka kesempatan buat Kamu yang ingin menjajal pengalaman kerja di bisnis yang dijalankan Seven Inc')),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konten Hero',
                'verbose_name_plural': 'Konten Hero',
            },
        ),
        migrations.CreateModel(
            name='KontakContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_telepon', models.CharField(default='0895 2900 2944', max_length=30)),
                ('alamat', models.TextField(default='Jl. Janti Gg. Arjuna No. 59, Karangjambe, Banguntapan, Bantul, Yogyakarta 55198')),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konten Kontak',
                'verbose_name_plural': 'Konten Kontak',
            },
        ),
        migrations.CreateModel(
            name='SyaratItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks', models.TextField(help_text='Isi poin syarat. Boleh multi-baris.')),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Syarat & Ketentuan',
                'verbose_name_plural': 'Syarat & Ketentuan',
                'ordering': ['urutan', 'id'],
            },
        ),
    ]
