# Generated by Django 6.1 on 2026-09-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syaratitem',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto pendukung untuk poin syarat ini (opsional).', null=True, upload_to='syarat_foto/'),
        ),
    ]
