# Generated by Django 6.1 on 2026-08-13 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Nama posisi, misal 'UI/UX Designer'.", max_length=100)),
                ('sub_label', models.CharField(blank=True, help_text="Teks baris kedua di kartu, misal 'Frontend/Backend'. Boleh kosong.", max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='Dipakai di URL /posisi/<slug>. Kosongkan untuk dibuat otomatis dari label.', max_length=120, unique=True)),
                ('icon', models.ImageField(blank=True, help_text='Icon/ilustrasi untuk kartu posisi ini (svg/png).', null=True, upload_to='divisi_icons/')),
                ('deskripsi', models.TextField(help_text='Deskripsi singkat divisi, ditampilkan di halaman detail.')),
                ('gform_link', models.URLField(help_text='Link Google Form pendaftaran untuk posisi ini.', max_length=500)),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Urutan tampil di halaman utama (angka kecil tampil duluan).')),
                ('aktif', models.BooleanField(default=True, help_text='Matikan (uncheck) untuk sembunyikan posisi ini dari website tanpa menghapus datanya.')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Divisi Magang',
                'verbose_name_plural': 'Divisi Magang',
                'ordering': ['urutan', 'label'],
            },
        ),
        migrations.CreateModel(
            name='JobdeskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks', models.CharField(max_length=255)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobdesk_items', to='divisi.divisi')),
            ],
            options={
                'verbose_name': 'Item Jobdesk',
                'verbose_name_plural': 'Item Jobdesk',
                'ordering': ['urutan', 'id'],
            },
        ),
    ]
