# Generated by Django 6.1 on 2026-08-14 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text="Nama internal buat memudahkan cari di admin, misal 'syarat_magang'.", max_length=100)),
                ('keywords', models.TextField(help_text='Kata kunci pemicu, pisahkan dengan koma. Contoh: syarat, ketentuan, persyaratan daftar')),
                ('jawaban', models.TextField(help_text='Jawaban yang langsung dikirim kalau salah satu keyword cocok.')),
                ('prioritas', models.PositiveIntegerField(default=0, help_text='Kalau pesan user cocok beberapa intent sekaligus, yang angkanya lebih besar dipakai duluan.')),
                ('aktif', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Intent / FAQ Chatbot',
                'verbose_name_plural': 'Intent / FAQ Chatbot',
                'ordering': ['-prioritas', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(help_text="Misal 'Jam Operasional', 'Durasi Magang', 'Cara Daftar'.", max_length=150)),
                ('isi', models.TextField(help_text='Isi informasi, tulis dengan natural -- ini akan dibaca AI sebagai konteks jawaban.')),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Info Tambahan Chatbot',
                'verbose_name_plural': 'Info Tambahan Chatbot',
                'ordering': ['urutan', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_telepon', models.CharField(db_index=True, max_length=30, unique=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('terakhir_aktif', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengunjung Chat',
                'verbose_name_plural': 'Pengunjung Chat',
                'ordering': ['-terakhir_aktif'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengirim', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('sumber', models.CharField(choices=[('static', 'Static / Intent'), ('ollama', 'Ollama'), ('system', 'System')], default='system', max_length=10)),
                ('pesan', models.TextField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.visitor')),
            ],
            options={
                'verbose_name': 'Pesan Chat',
                'verbose_name_plural': 'Riwayat Chat',
                'ordering': ['dibuat_pada'],
            },
        ),
    ]
