# Generated by Django 6.1 on 2026-08-14 09:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatVisitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('no_telepon', models.CharField(max_length=30, unique=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('terakhir_aktif', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengunjung Chat',
                'verbose_name_plural': 'Pengunjung Chat',
                'ordering': ['-terakhir_aktif'],
            },
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(blank=True, help_text="Pengelompokan, misal 'Sapaan', 'Syarat', 'Jadwal'. Bebas, cuma buat rapi di admin.", max_length=100)),
                ('keywords', models.JSONField(default=list, help_text='Daftar kata kunci pemicu, format list JSON. Contoh: ["syarat", "persyaratan", "daftar magang"]')),
                ('jawaban', models.TextField(help_text='Jawaban yang langsung dikirim kalau salah satu keyword di atas ketemu di pesan user.')),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Kalau pesan user cocok lebih dari 1 intent, yang urutannya lebih kecil menang.')),
                ('aktif', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Intent (Jawaban Statis)',
                'verbose_name_plural': 'Intent (Jawaban Statis)',
                'ordering': ['urutan', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('konten', models.TextField(help_text='Isi pengetahuan dalam bahasa natural. Ini yang dibaca Ollama sebagai konteks.')),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('aktif', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge Base',
                'verbose_name_plural': 'Knowledge Base',
                'ordering': ['urutan', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengirim', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('pesan', models.TextField()),
                ('sumber', models.CharField(blank=True, choices=[('static', 'Intent Statis'), ('ollama', 'Ollama (AI)'), ('system', 'Pesan Sistem')], help_text='Cuma relevan buat pesan dari bot: dijawab pakai intent statis atau Ollama.', max_length=10)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot_app.chatvisitor')),
            ],
            options={
                'verbose_name': 'Pesan Chat',
                'verbose_name_plural': 'Riwayat Chat',
                'ordering': ['dibuat_pada'],
            },
        ),
    ]
