# Generated by Django 6.1 on 2026-08-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='contoh_pertanyaan',
            field=models.JSONField(blank=True, default=list, help_text='List contoh kalimat yang mewakili intent ini, format list JSON. Makin banyak & variatif, makin akurat pencocokannya.'),
        ),
        migrations.AddField(
            model_name='intent',
            name='nama',
            field=models.SlugField(blank=True, help_text="ID unik intent, misal 'tanya_syarat_pendaftaran'. Kosongkan untuk auto dari kategori.", max_length=100),
        ),
        migrations.AlterField(
            model_name='intent',
            name='jawaban',
            field=models.TextField(help_text='Jawaban yang dikirim kalau intent ini yang paling cocok dengan pesan user.'),
        ),
        migrations.AlterField(
            model_name='intent',
            name='kategori',
            field=models.CharField(blank=True, help_text="Pengelompokan/context, misal 'informasi_program.syarat_pendaftaran'. Bebas, cuma buat rapi di admin.", max_length=150),
        ),
        migrations.AlterField(
            model_name='intent',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='(Opsional) Daftar kata kunci untuk pencocokan cepat/pasti, format list JSON. Boleh dikosongkan.'),
        ),
        migrations.AlterField(
            model_name='intent',
            name='urutan',
            field=models.PositiveIntegerField(default=0, help_text='Kalau ada beberapa intent dengan skor kemiripan setara, yang urutannya lebih kecil menang.'),
        ),
    ]
