# Generated by Django 6.1 on 2026-08-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0002_intent_contoh_pertanyaan_intent_nama_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sumber',
            field=models.CharField(blank=True, choices=[('static', 'Intent Statis'), ('ollama', 'Ollama (AI)'), ('guard', 'Ditolak (Di Luar Topik)'), ('system', 'Pesan Sistem')], help_text='Cuma relevan buat pesan dari bot: dijawab pakai intent statis atau Ollama.', max_length=10),
        ),
    ]
